server:
  port: 8888

spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
      primary-dialect: org.hibernate.dialect.MySQL5Dialect
      secondary-dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://94.191.10.75:3306/book?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 159357
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.tcj.red_book.entity.pojo

#logging:
#  level:
#    com:
#      tcj:
#        dao : debug
#

book:
  encoder:
    crypt:
      secret: 325454265
      strength: 10
  jwt:
    user:
      expire: 3000
      cookieName: REMOKE_TOKEN
#    pubKeyPath: D:/home/smoke/keys/id_rsa.pub
#    priKeyPath: D:/home/smoke/keys/id_rsa
    pubKeyPath: /home/ubuntu/key/id_rsa.pub
    priKeyPath: /home/ubuntu/key/id_rsa
